name: mastra-workflow-tests

services:
  inngest:
    container_name: inngest-durable-poc
    image: inngest/inngest:v1.16.1
    command: inngest dev -p 4100 -u http://host.docker.internal:4101/inngest/api --poll-interval=1
    ports:
      - '4100:4100'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
