services:
  jaeger:
    image: jaegertracing/jaeger:2.10.0@sha256:8c593d8048d86334eb52dba26633b6c846b8ecbe5c22905702c932ae97baeb42
    container_name: jaeger
    restart: always
    ports:
      - 16686:16686
      - 4318:4318
